sudo: required
services:
  - docker

before_install:
  - docker build -t tlsingh1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tlsingh1/react-test npm test

after_success:
  - docker build -t tlsingh1/multi-client ./client
  - docker build -t tlsingh1/multi-nginx ./nginx
  - docker build -t tlsingh1/multi-server /server
  - docker build -t tlsingh1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tlsingh1/multi-client
  - docker push tlsingh1/multi-nginx
  - docker push tlsingh1/multi-server
  - docker push tlsingh1/multi-worker
